apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: listener
  name: listener
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: listener
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: listener
    spec:
      containers:
        - args:
            - sh
            - -c
            - sleep 10 && python -u main.py
          image: listener:latest
          imagePullPolicy: IfNotPresent
          name: listener
          resources: {}
      restartPolicy: Always
      volumes:
        - name: listener-claim0
          persistentVolumeClaim:
            claimName: listener-claim0
status: {}
